const CLEAR_ALL_DONE = "CLEAR_ALL_DONE";
const CHANGE_CHECKBOX_STATE_SUCCESS = "CHANGE_CHECKBOX_STATE_SUCCESS";
const CHANGE_CHECKBOX_STATE_FAIL = "CHANGE_CHECKBOX_STATE_FAIL";
const HANDLE_ADD_DATA_SUCCESS = "HANDLE_ADD_DATA_SUCCESS";
const HANDLE_ADD_DATA_FAIL = "HANDLE_ADD_DATA_FAIL";
const HANDLE_MARK_AS_NOT_DONE_SUCCESS = "HANDLE_MARK_AS_NOT_DONE_SUCCESS";
const HANDLE_MARK_AS_NOT_DONE_FAIL = "HANDLE_MARK_AS_NOT_DONE_FAIL;";
const HANDLE_MARK_AS_DONE_SUCCESS = "HANDLE_MARK_AS_DONE_SUCCESS";
const HANDLE_MARK_AS_DONE_FAIL = "HANDLE_MARK_AS_DONE_FAIL";
const GET_TO_DO_DATA_SUCCESS = "GET_TO_DO_DATA_SUCCESS";
const GET_TO_DO_DATA_FAIL = "GET_TO_DO_DATA_SUCCESS_FAIL";
const CLEAR_ALL_DONE_SUCCESS = "CLEAR_ALL_DONE_SUCCESS";
const CLEAR_ALL_DONE_FAIL = "CLEAR_ALL_DONE_FAIL";
const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";

export const ActionsTypes = {
  CLEAR_ALL_DONE,
  CHANGE_CHECKBOX_STATE_SUCCESS,
  CHANGE_CHECKBOX_STATE_FAIL,
  HANDLE_ADD_DATA_SUCCESS,
  HANDLE_ADD_DATA_FAIL,
  HANDLE_MARK_AS_NOT_DONE_SUCCESS,
  HANDLE_MARK_AS_NOT_DONE_FAIL,
  HANDLE_MARK_AS_DONE_SUCCESS,
  HANDLE_MARK_AS_DONE_FAIL,
  GET_TO_DO_DATA_SUCCESS,
  GET_TO_DO_DATA_FAIL,
  CLEAR_ALL_DONE_SUCCESS,
  CLEAR_ALL_DONE_FAIL,
  DELETE_ITEM_SUCCESS,
  DELETE_ITEM_FAIL
};
