export enum ActionsTypes {
  CLEAR_ALL_DONE,
  CHANGE_CHECKBOX_STATE_SUCCESS,
  CHANGE_CHECKBOX_STATE_FAIL,
  HANDLE_ADD_DATA_SUCCESS,
  HANDLE_ADD_DATA_FAIL,
  HANDLE_MARK_AS_NOT_DONE_SUCCESS,
  HANDLE_MARK_AS_NOT_DONE_FAIL,
  HANDLE_MARK_AS_DONE_SUCCESS,
  HANDLE_MARK_AS_DONE_FAIL,
  GET_TO_DO_DATA_SUCCESS,
  GET_TO_DO_DATA_FAIL,
  CLEAR_ALL_DONE_SUCCESS,
  CLEAR_ALL_DONE_FAIL,
  DELETE_ITEM_SUCCESS,
  DELETE_ITEM_FAIL
}
